### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by geoffdavis92** [geoffdavis92/react-floodgate#11]
Floodgate doesn't need `react` or `react-dom` as `dependencies`; move `react` to `peerDependencies`, and `react-dom` to `devDependencies` so they are properly included/not included during package installation.

Checklist:
- [ ] Remove `react` and `react-dom` from the project's dependencies using [yarn](https://yarnpkg.com)
- [ ] Add `react@16` to the project using the `-P | --peer` option
- [ ] Add `react-dom@16` to the project using the `-D | --dev` option

**Comment by kostimarko** [comment]
Hi, I can take this on.

**Comment by geoffdavis92** [comment]
@kostimarko go for it!
