### ISSUE TITLE
Write CODE_OF_CONDUCT

### ISSUE THREAD

**Issue by geoffdavis92** [geoffdavis92/react-floodgate#5]
Add a Code of Conduct file. More info on CoC [here](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/).

**Comment by josteink** [comment]
I'll take it :)

**Comment by geoffdavis92** [comment]
@josteink Thanks! I'm about to log off, but I'll take a look in the morning.

**Comment by geoffdavis92** [comment]
Closed by #10
